### PR TITLE
column range selection, webmozart dependency, fix column range query

### PR DESCRIPTION
**Pull request by mature-woman**

### CODE REVIEW

**Comment by mature-woman** [comment]
A lot of unit tests broke due to changes in SheetRange.php. However, the originally supplied code does not work for me. My fixes work and parse data from Google Sheets.

**Comment by norberttech** [comment]
> A lot of unit tests broke due to changes in SheetRange.php. However, the originally supplied code does not work for me. My fixes work and parse data from Google Sheets.

Any idea why the existing code is not working for you? This can't be merged if it's breaking existing tests unless we prove that tests are wrong and code is not usable at all.

**Comment by mature-woman** [comment]
> > A lot of unit tests broke due to changes in SheetRange.php. However, the originally supplied code does not work for me. My fixes work and parse data from Google Sheets.
> 
> Any idea why the existing code is not working for you? This can't be merged if it's breaking existing tests unless we prove that tests are wrong and code is not usable at all.

I don't know why, but the formation of the link for the request does not work. I tried to edit directly in the browser and it didn't work there either. I looked at how google generates the link itself and rewrote the code.

In the first screenshot, the original code:
https://docs.google.com/spreadsheets/d/{DOCUMENT_ID}/edit#gid={SHEET_ID}range={SHEET_ID}!A1:Z1
Снимок экрана от 2023-06-05 15-08-38

In the second screenshot, the rewritten code:
https://docs.google.com/spreadsheets/d/{DOCUMENT_ID}/edit#gid={SHEET_ID}range=A1:Z1
Снимок экрана от 2023-06-05 15-09-47

As I understand it, unit tests expect behavior with "{SHEET_ID}!A1:I1", so they fail.

{SHEET_ID}!A1:I1 does not work for me
maybe I'm doing something wrong?
this is my first experience with google sheets

**Comment by norberttech** [comment]
thanks for the detailed explanation @mature-woman I really appreciate the effort! 
@jwojtyra-aterian could you maybe take a look and let us know what you think since you worked on this adapter?

**Comment by norberttech** [comment]
hey @mature-woman I checked docs and it seems that format `{SHEET_ID}!B1:B21` is perfectly fine, please take al look here: 

https://www.nidup.io/blog/manipulate-google-sheets-in-php-with-api#fetch-a-few-rows-by-using-a-range

Are you sure you are using correct `SHEET_ID`?

**Comment by ghost** [comment]
Format is good I would definitely check out `SHEET_NAME`.

**Comment by mature-woman** [comment]
> hey @mature-woman I checked docs and it seems that format `{SHEET_ID}!B1:B21` is perfectly fine, please take al look here:
> 
> https://www.nidup.io/blog/manipulate-google-sheets-in-php-with-api#fetch-a-few-rows-by-using-a-range
> 
> Are you sure you are using correct `SHEET_ID`?

image

https://docs.google.com/spreadsheets/d/1AKuISHKVN7H1NePKhg95ZjdQbEeMyx2ZFjRePWnX0ds/edit#gid=1434798988

SHEET_ID is "1434798988"?
I took it from here

**Comment by mature-woman** [comment]
The sheet is called "ДАННЫЕ (сотрудников)". If I use this name, then nothing works. Is it encoded for url? Cyrillic characters are included in UTF-8, so it should work.

**Comment by mature-woman** [comment]
I learned more about your framework and "googleapis/google-api-php-client" and realized that my pull request is useless

Thanks for answers.
I apologize for wasting your time.

Everything works
image

**Comment by norberttech** [comment]
I'm glad it worked 👍

**Pull request closed without merging**
