### PR TITLE
Fix for signing PHAR in CI

### PR DESCRIPTION
**Pull request by stloyd**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>Fix for signing PHAR in CI</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

Since version 2.0 of GPG `--batch` flag must be used if a `--passphrase` was used.

### CODE REVIEW

**Comment by flavioheleno** [comment]
nice catch, I'll follow up with updates to my own repositories as well :)

**Comment by flavioheleno** [comment]
Hey, on my local tests, I had to add `--pinentry-mode loopback` to make it work, otherwise it would wait for input forever

**Comment by stloyd** [comment]
@flavioheleno true, seems to be required in newer versions. Fix: https://github.com/flow-php/flow/pull/705

**Comment by norberttech** [comment]
There was a small typo, but after all adjustments, I tested it on my fork, and worked 🎉 thanks guys! 

#707

**Pull request merged**
