### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>Corrected misspellings</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

Found some misspellings.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please consider [running `typos` in CI](https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/spelling.yml#L33).
Here is the configuration used.

`.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
    "CHANGELOG.md",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    '"nam |',
    '"country_code": "[A-Z]{2}",',
    "\\['nam.e'\\],",
    "- \\[[0-9a-z]{6}\\]\\(https://github\\.com/flow-php/flow",
    "'BA', 'AB',",
    "range `BA`",
    "Mata-Utu",
]
```

**Comment by norberttech** [comment]
Thanks! However, could you please revert the changes on the changelog? CHANGELOG.md is auto-generated from pull requests/commits. Correcting it won't give us much since it will be replaced the next time we regenerate it.

**Comment by szepeviktor** [comment]
> please revert the changes on the changelog

Done.

**Comment by szepeviktor** [comment]
@norberttech Please consider changing a few PR's typos.
e.g. #153

**Comment by norberttech** [comment]
Yup, it's on my todo list 👍 A GitHub workflow action that would go through PR changelog  section looking for typos would be nice to have

**Comment by szepeviktor** [comment]
> that would go through PR changelog section looking for typos

You can see those typos in the last commit here.

**Comment by norberttech** [comment]
yeah, but that won't prevent people (and me) from making more typos in the future, it's a one-time cleanup that I will do (eventually) but would be nice to not have to go through this again

**Comment by szepeviktor** [comment]
What fields should be checked in a PR?

**Pull request merged**
