### PR TITLE
Improve quality of snappy implementation

### PR DESCRIPTION
**Pull request by stloyd**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    <li>Improve quality of snappy implementation</li>
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

### CODE REVIEW

**Comment by norberttech** [comment]
Hmm, looking at those changes, I don't think this will bring any visible performance improvements into the general implementation. It makes the code slightly cleaner (and it's a good enough reason to merge it), but it seems irrelevant from the entire algorithm performance point of view. 
Have you tried to execute the benchmark from readme to see if there was any improvement?

**Comment by stloyd** [comment]
Yes, both profiles were generated using the example from the readme with just small adjustments (hardcoded faker data & skip of extension run).

**Comment by norberttech** [comment]
Is there any performance impact on the initial benchmark?

**Comment by norberttech** [comment]
I'm gonna merge this regardless, however, if there is no visible performance impact, I would rename this PR and changelog into "improve code readability of snappy implementation" from "improve performance of snappy implementation". 
But if there is any impact on the original benchmark, then let's make it clear in the description how much it improved the performance. 
The screenshot of the profile does not clearly answer that question as it does not even show what was the portion of data used in that profile. `-272ms` from `6s` and millions of executions is almost not relevant, however `-272ms` from `300ms` sounds like a big win.

**Comment by stloyd** [comment]
@norberttech I have renamed the commit & PR, cause I could not reproduce the result enough (used also sampling in profiler) to confirm performance improvements.

**Comment by norberttech** [comment]
Thanks!

**Pull request merged**
