### PR TITLE
fix path in windows

### PR DESCRIPTION
**Pull request by yangweijie**
only linux os need add DIRECTORY_SEPARATOR if path not begins with '/'

<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>path wrong in windows.</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

### CODE REVIEW

**Comment by norberttech** [comment]
hey @yangweijie sorry I'm not sure if I follow, could you elaborate a bit more on this one and maybe provide some tests that would cover the changes from this PR?

**Comment by yangweijie** [comment]
If you use in windows ， u can find the bug easyly.
image
image
with fixed by just one line code for platform judgement 
image

**Comment by yangweijie** [comment]
the path generated by path concat by `runtime_path` function  in ThinkPHP framework. Acturely , The const string 'C:\git\tp\runtime\log\20241103.parquet' which a realpah for a file exists will take the same effect.

image

**Comment by norberttech** [comment]
I'm on the fence about this one. To do it right we would need first: 

- setup a windows runtime on GitHub Actions
- adjust tests and whole codebase for Windows 
- **provide Windows Support** 

However, due to my limited availability, I do not see a possibility for me to work on that in the near future. 
So to make it happen someone would need to sponsor that feature request or take care of the whole thing and become a maintainer responsible for the Windows support only. 

In its current form and shape this PR can't be merged as: 

- existing tests are failing
- there are no tests covering this fix 
- not a single test is executed on Windows runtime. 

I'm closing this one for now but will keep [Windows Support](https://github.com/orgs/flow-php/projects/1/views/3?pane=issue&itemId=89917186) in the Roadmap in case anyone would be ever interested in working on it

**Pull request closed without merging**
