### PR TITLE
Fixing bug when xml->deep > 1 and previousDeep > xml->deep

### PR DESCRIPTION
**Pull request by FunkyOz**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>Change behavior of xml adapter when xml->deep > 1 and previousDeep > xml->deep</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

The intent of thi PR is to fix a problem when an xml file is deeper than 2 tags.
I thinks it's better to decrement $previousDeep to $xml->deep as describe in this [issue](https://github.com/flow-php/flow/issues/590)

### CODE REVIEW

**Comment by norberttech** [comment]
Thanks @FunkyOz!! 
Could you please resolve the conflict and look at the static analyze results? Locally you can execute whole test suite through `composer build`

**Comment by FunkyOz** [comment]
Sure, I do it, thanks :)

**Comment by FunkyOz** [comment]
@norberttech I'm an issue with `composer build`.
The command `tools/phpstan/vendor/bin/phpstan analyze -c phpstan.neon --memory-limit=-1` fail with errors

```shell
 Line   adapter/etl-adapter-xml/src/Flow/ETL/Adapter/XML/XMLReaderExtractor.php               
 ------ -------------------------------------------------------------------------------------- 
  50     Access to an undefined property XMLReader::$nodeType.                                 
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  51     Access to an undefined property XMLReader::$depth.                                    
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  53     Access to an undefined property XMLReader::$name.                                     
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  56     Access to an undefined property XMLReader::$depth.                                    
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  57     Access to an undefined property XMLReader::$name.                                     
         💡 Learn more: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
 ------ -------------------------------------------------------------------------------------- 


                                                                                                                        
 [ERROR] Found 5 errors                                                                                                 
                                                                                                                        

Script tools/phpstan/vendor/bin/phpstan analyze -c phpstan.neon --memory-limit=-1 handling the static:analyze event returned with error code 1
Script @static:analyze was called via build
```

But this properties are php built in. How do you resolve?

Also PR tell that there are conflics that I don't see.

Thk

**Comment by norberttech** [comment]
Let me take care of this from here, https://github.com/flow-php/flow/pull/593 should contain your original commits + my rebase fix

**Pull request closed without merging**
